on:
  push:
    branches:
      - master    









jobs:
  build:
    runs-on: ubuntu-latest
             
    steps: 
      - name: 'print folder content before' 
        run: ls
        
      - uses: actions/checkout@v3

      - name: 'print folder content after' 
        run: ls -a
